zuul:
  routes:
    adminui:
      path: /ui/**
      url: http://localhost:4200/ui/
logging:
  level:
    org.springframework.web: 'debug'
    org.springframework.hateoas: 'debug'

spring:
  jackson:
    serialization:
      indent_output: 'true'